// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: fund.proto

package fund

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FundService_Ping_FullMethodName                   = "/fund.FundService/Ping"
	FundService_CreateFund_FullMethodName             = "/fund.FundService/CreateFund"
	FundService_ListFunds_FullMethodName              = "/fund.FundService/ListFunds"
	FundService_GetFund_FullMethodName                = "/fund.FundService/GetFund"
	FundService_UpdateFund_FullMethodName             = "/fund.FundService/UpdateFund"
	FundService_DeleteFund_FullMethodName             = "/fund.FundService/DeleteFund"
	FundService_InvestFund_FullMethodName             = "/fund.FundService/InvestFund"
	FundService_WithdrawFund_FullMethodName           = "/fund.FundService/WithdrawFund"
	FundService_GetBankPositions_FullMethodName       = "/fund.FundService/GetBankPositions"
	FundService_GetMyPositions_FullMethodName         = "/fund.FundService/GetMyPositions"
	FundService_TransferFundsByManager_FullMethodName = "/fund.FundService/TransferFundsByManager"
	FundService_ValidateFundAccount_FullMethodName    = "/fund.FundService/ValidateFundAccount"
	FundService_UpdateFundHolding_FullMethodName      = "/fund.FundService/UpdateFundHolding"
	FundService_GetFundPortfolio_FullMethodName       = "/fund.FundService/GetFundPortfolio"
)

// FundServiceClient is the client API for FundService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FundServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	CreateFund(ctx context.Context, in *CreateFundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error)
	GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	UpdateFund(ctx context.Context, in *UpdateFundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	DeleteFund(ctx context.Context, in *DeleteFundRequest, opts ...grpc.CallOption) (*DeleteFundResponse, error)
	InvestFund(ctx context.Context, in *InvestFundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	WithdrawFund(ctx context.Context, in *WithdrawFundRequest, opts ...grpc.CallOption) (*FundResponse, error)
	GetBankPositions(ctx context.Context, in *GetBankPositionsRequest, opts ...grpc.CallOption) (*GetBankPositionsResponse, error)
	GetMyPositions(ctx context.Context, in *GetMyPositionsRequest, opts ...grpc.CallOption) (*GetMyPositionsResponse, error)
	TransferFundsByManager(ctx context.Context, in *TransferFundsByManagerRequest, opts ...grpc.CallOption) (*TransferFundsByManagerResponse, error)
	ValidateFundAccount(ctx context.Context, in *ValidateFundAccountRequest, opts ...grpc.CallOption) (*ValidateFundAccountResponse, error)
	UpdateFundHolding(ctx context.Context, in *UpdateFundHoldingRequest, opts ...grpc.CallOption) (*UpdateFundHoldingResponse, error)
	GetFundPortfolio(ctx context.Context, in *GetFundPortfolioRequest, opts ...grpc.CallOption) (*GetFundPortfolioResponse, error)
}

type fundServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFundServiceClient(cc grpc.ClientConnInterface) FundServiceClient {
	return &fundServiceClient{cc}
}

func (c *fundServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FundService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) CreateFund(ctx context.Context, in *CreateFundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, FundService_CreateFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ListFunds(ctx context.Context, in *ListFundsRequest, opts ...grpc.CallOption) (*ListFundsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFundsResponse)
	err := c.cc.Invoke(ctx, FundService_ListFunds_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetFund(ctx context.Context, in *GetFundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, FundService_GetFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) UpdateFund(ctx context.Context, in *UpdateFundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, FundService_UpdateFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) DeleteFund(ctx context.Context, in *DeleteFundRequest, opts ...grpc.CallOption) (*DeleteFundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFundResponse)
	err := c.cc.Invoke(ctx, FundService_DeleteFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) InvestFund(ctx context.Context, in *InvestFundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, FundService_InvestFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) WithdrawFund(ctx context.Context, in *WithdrawFundRequest, opts ...grpc.CallOption) (*FundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FundResponse)
	err := c.cc.Invoke(ctx, FundService_WithdrawFund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetBankPositions(ctx context.Context, in *GetBankPositionsRequest, opts ...grpc.CallOption) (*GetBankPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankPositionsResponse)
	err := c.cc.Invoke(ctx, FundService_GetBankPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetMyPositions(ctx context.Context, in *GetMyPositionsRequest, opts ...grpc.CallOption) (*GetMyPositionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyPositionsResponse)
	err := c.cc.Invoke(ctx, FundService_GetMyPositions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) TransferFundsByManager(ctx context.Context, in *TransferFundsByManagerRequest, opts ...grpc.CallOption) (*TransferFundsByManagerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransferFundsByManagerResponse)
	err := c.cc.Invoke(ctx, FundService_TransferFundsByManager_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) ValidateFundAccount(ctx context.Context, in *ValidateFundAccountRequest, opts ...grpc.CallOption) (*ValidateFundAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateFundAccountResponse)
	err := c.cc.Invoke(ctx, FundService_ValidateFundAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) UpdateFundHolding(ctx context.Context, in *UpdateFundHoldingRequest, opts ...grpc.CallOption) (*UpdateFundHoldingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFundHoldingResponse)
	err := c.cc.Invoke(ctx, FundService_UpdateFundHolding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fundServiceClient) GetFundPortfolio(ctx context.Context, in *GetFundPortfolioRequest, opts ...grpc.CallOption) (*GetFundPortfolioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFundPortfolioResponse)
	err := c.cc.Invoke(ctx, FundService_GetFundPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FundServiceServer is the server API for FundService service.
// All implementations must embed UnimplementedFundServiceServer
// for forward compatibility.
type FundServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	CreateFund(context.Context, *CreateFundRequest) (*FundResponse, error)
	ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error)
	GetFund(context.Context, *GetFundRequest) (*FundResponse, error)
	UpdateFund(context.Context, *UpdateFundRequest) (*FundResponse, error)
	DeleteFund(context.Context, *DeleteFundRequest) (*DeleteFundResponse, error)
	InvestFund(context.Context, *InvestFundRequest) (*FundResponse, error)
	WithdrawFund(context.Context, *WithdrawFundRequest) (*FundResponse, error)
	GetBankPositions(context.Context, *GetBankPositionsRequest) (*GetBankPositionsResponse, error)
	GetMyPositions(context.Context, *GetMyPositionsRequest) (*GetMyPositionsResponse, error)
	TransferFundsByManager(context.Context, *TransferFundsByManagerRequest) (*TransferFundsByManagerResponse, error)
	ValidateFundAccount(context.Context, *ValidateFundAccountRequest) (*ValidateFundAccountResponse, error)
	UpdateFundHolding(context.Context, *UpdateFundHoldingRequest) (*UpdateFundHoldingResponse, error)
	GetFundPortfolio(context.Context, *GetFundPortfolioRequest) (*GetFundPortfolioResponse, error)
	mustEmbedUnimplementedFundServiceServer()
}

// UnimplementedFundServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFundServiceServer struct{}

func (UnimplementedFundServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFundServiceServer) CreateFund(context.Context, *CreateFundRequest) (*FundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateFund not implemented")
}
func (UnimplementedFundServiceServer) ListFunds(context.Context, *ListFundsRequest) (*ListFundsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunds not implemented")
}
func (UnimplementedFundServiceServer) GetFund(context.Context, *GetFundRequest) (*FundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFund not implemented")
}
func (UnimplementedFundServiceServer) UpdateFund(context.Context, *UpdateFundRequest) (*FundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFund not implemented")
}
func (UnimplementedFundServiceServer) DeleteFund(context.Context, *DeleteFundRequest) (*DeleteFundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteFund not implemented")
}
func (UnimplementedFundServiceServer) InvestFund(context.Context, *InvestFundRequest) (*FundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvestFund not implemented")
}
func (UnimplementedFundServiceServer) WithdrawFund(context.Context, *WithdrawFundRequest) (*FundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WithdrawFund not implemented")
}
func (UnimplementedFundServiceServer) GetBankPositions(context.Context, *GetBankPositionsRequest) (*GetBankPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBankPositions not implemented")
}
func (UnimplementedFundServiceServer) GetMyPositions(context.Context, *GetMyPositionsRequest) (*GetMyPositionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyPositions not implemented")
}
func (UnimplementedFundServiceServer) TransferFundsByManager(context.Context, *TransferFundsByManagerRequest) (*TransferFundsByManagerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TransferFundsByManager not implemented")
}
func (UnimplementedFundServiceServer) ValidateFundAccount(context.Context, *ValidateFundAccountRequest) (*ValidateFundAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateFundAccount not implemented")
}
func (UnimplementedFundServiceServer) UpdateFundHolding(context.Context, *UpdateFundHoldingRequest) (*UpdateFundHoldingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateFundHolding not implemented")
}
func (UnimplementedFundServiceServer) GetFundPortfolio(context.Context, *GetFundPortfolioRequest) (*GetFundPortfolioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFundPortfolio not implemented")
}
func (UnimplementedFundServiceServer) mustEmbedUnimplementedFundServiceServer() {}
func (UnimplementedFundServiceServer) testEmbeddedByValue()                     {}

// UnsafeFundServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FundServiceServer will
// result in compilation errors.
type UnsafeFundServiceServer interface {
	mustEmbedUnimplementedFundServiceServer()
}

func RegisterFundServiceServer(s grpc.ServiceRegistrar, srv FundServiceServer) {
	// If the following call panics, it indicates UnimplementedFundServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FundService_ServiceDesc, srv)
}

func _FundService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_CreateFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).CreateFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_CreateFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).CreateFund(ctx, req.(*CreateFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ListFunds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ListFunds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_ListFunds_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ListFunds(ctx, req.(*ListFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_GetFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetFund(ctx, req.(*GetFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_UpdateFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).UpdateFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_UpdateFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).UpdateFund(ctx, req.(*UpdateFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_DeleteFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).DeleteFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_DeleteFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).DeleteFund(ctx, req.(*DeleteFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_InvestFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvestFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).InvestFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_InvestFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).InvestFund(ctx, req.(*InvestFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_WithdrawFund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawFundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).WithdrawFund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_WithdrawFund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).WithdrawFund(ctx, req.(*WithdrawFundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetBankPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetBankPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_GetBankPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetBankPositions(ctx, req.(*GetBankPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetMyPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetMyPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_GetMyPositions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetMyPositions(ctx, req.(*GetMyPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_TransferFundsByManager_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransferFundsByManagerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).TransferFundsByManager(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_TransferFundsByManager_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).TransferFundsByManager(ctx, req.(*TransferFundsByManagerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_ValidateFundAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateFundAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).ValidateFundAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_ValidateFundAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).ValidateFundAccount(ctx, req.(*ValidateFundAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_UpdateFundHolding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFundHoldingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).UpdateFundHolding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_UpdateFundHolding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).UpdateFundHolding(ctx, req.(*UpdateFundHoldingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FundService_GetFundPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFundPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FundServiceServer).GetFundPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FundService_GetFundPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FundServiceServer).GetFundPortfolio(ctx, req.(*GetFundPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FundService_ServiceDesc is the grpc.ServiceDesc for FundService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FundService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fund.FundService",
	HandlerType: (*FundServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FundService_Ping_Handler,
		},
		{
			MethodName: "CreateFund",
			Handler:    _FundService_CreateFund_Handler,
		},
		{
			MethodName: "ListFunds",
			Handler:    _FundService_ListFunds_Handler,
		},
		{
			MethodName: "GetFund",
			Handler:    _FundService_GetFund_Handler,
		},
		{
			MethodName: "UpdateFund",
			Handler:    _FundService_UpdateFund_Handler,
		},
		{
			MethodName: "DeleteFund",
			Handler:    _FundService_DeleteFund_Handler,
		},
		{
			MethodName: "InvestFund",
			Handler:    _FundService_InvestFund_Handler,
		},
		{
			MethodName: "WithdrawFund",
			Handler:    _FundService_WithdrawFund_Handler,
		},
		{
			MethodName: "GetBankPositions",
			Handler:    _FundService_GetBankPositions_Handler,
		},
		{
			MethodName: "GetMyPositions",
			Handler:    _FundService_GetMyPositions_Handler,
		},
		{
			MethodName: "TransferFundsByManager",
			Handler:    _FundService_TransferFundsByManager_Handler,
		},
		{
			MethodName: "ValidateFundAccount",
			Handler:    _FundService_ValidateFundAccount_Handler,
		},
		{
			MethodName: "UpdateFundHolding",
			Handler:    _FundService_UpdateFundHolding_Handler,
		},
		{
			MethodName: "GetFundPortfolio",
			Handler:    _FundService_GetFundPortfolio_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fund.proto",
}
