// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: fund.proto

package fund

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_fund_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_fund_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateFundRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Name                string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,3,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,4,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	CreatedById         int64                  `protobuf:"varint,5,opt,name=created_by_id,json=createdById,proto3" json:"created_by_id,omitempty"` // employee ID of creator
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateFundRequest) Reset() {
	*x = CreateFundRequest{}
	mi := &file_fund_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateFundRequest) ProtoMessage() {}

func (x *CreateFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateFundRequest.ProtoReflect.Descriptor instead.
func (*CreateFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{2}
}

func (x *CreateFundRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateFundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateFundRequest) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *CreateFundRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *CreateFundRequest) GetCreatedById() int64 {
	if x != nil {
		return x.CreatedById
	}
	return 0
}

type UpdateFundRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,4,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateFundRequest) Reset() {
	*x = UpdateFundRequest{}
	mi := &file_fund_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFundRequest) ProtoMessage() {}

func (x *UpdateFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFundRequest.ProtoReflect.Descriptor instead.
func (*UpdateFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateFundRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateFundRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateFundRequest) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *UpdateFundRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

type DeleteFundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFundRequest) Reset() {
	*x = DeleteFundRequest{}
	mi := &file_fund_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFundRequest) ProtoMessage() {}

func (x *DeleteFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFundRequest.ProtoReflect.Descriptor instead.
func (*DeleteFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteFundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFundResponse) Reset() {
	*x = DeleteFundResponse{}
	mi := &file_fund_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFundResponse) ProtoMessage() {}

func (x *DeleteFundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFundResponse.ProtoReflect.Descriptor instead.
func (*DeleteFundResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{5}
}

type ListFundsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ManagerIdFilter int64                  `protobuf:"varint,1,opt,name=manager_id_filter,json=managerIdFilter,proto3" json:"manager_id_filter,omitempty"` // 0 = no filter
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFundsRequest) Reset() {
	*x = ListFundsRequest{}
	mi := &file_fund_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFundsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFundsRequest) ProtoMessage() {}

func (x *ListFundsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFundsRequest.ProtoReflect.Descriptor instead.
func (*ListFundsRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{6}
}

func (x *ListFundsRequest) GetManagerIdFilter() int64 {
	if x != nil {
		return x.ManagerIdFilter
	}
	return 0
}

type GetFundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFundRequest) Reset() {
	*x = GetFundRequest{}
	mi := &file_fund_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFundRequest) ProtoMessage() {}

func (x *GetFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFundRequest.ProtoReflect.Descriptor instead.
func (*GetFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{7}
}

func (x *GetFundRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FundResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description         string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	MinimumContribution float64                `protobuf:"fixed64,4,opt,name=minimum_contribution,json=minimumContribution,proto3" json:"minimum_contribution,omitempty"`
	ManagerId           int64                  `protobuf:"varint,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	ManagerName         string                 `protobuf:"bytes,6,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
	LiquidAssets        float64                `protobuf:"fixed64,7,opt,name=liquid_assets,json=liquidAssets,proto3" json:"liquid_assets,omitempty"`
	FundValue           float64                `protobuf:"fixed64,8,opt,name=fund_value,json=fundValue,proto3" json:"fund_value,omitempty"`
	Profit              float64                `protobuf:"fixed64,9,opt,name=profit,proto3" json:"profit,omitempty"`
	AccountNumber       string                 `protobuf:"bytes,10,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	CreatedAt           string                 `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Active              bool                   `protobuf:"varint,12,opt,name=active,proto3" json:"active,omitempty"`
	AccountId           int64                  `protobuf:"varint,13,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *FundResponse) Reset() {
	*x = FundResponse{}
	mi := &file_fund_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FundResponse) ProtoMessage() {}

func (x *FundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FundResponse.ProtoReflect.Descriptor instead.
func (*FundResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{8}
}

func (x *FundResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FundResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FundResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FundResponse) GetMinimumContribution() float64 {
	if x != nil {
		return x.MinimumContribution
	}
	return 0
}

func (x *FundResponse) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *FundResponse) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *FundResponse) GetLiquidAssets() float64 {
	if x != nil {
		return x.LiquidAssets
	}
	return 0
}

func (x *FundResponse) GetFundValue() float64 {
	if x != nil {
		return x.FundValue
	}
	return 0
}

func (x *FundResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

func (x *FundResponse) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *FundResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *FundResponse) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *FundResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

type ListFundsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Funds         []*FundResponse        `protobuf:"bytes,1,rep,name=funds,proto3" json:"funds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFundsResponse) Reset() {
	*x = ListFundsResponse{}
	mi := &file_fund_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFundsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFundsResponse) ProtoMessage() {}

func (x *ListFundsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFundsResponse.ProtoReflect.Descriptor instead.
func (*ListFundsResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{9}
}

func (x *ListFundsResponse) GetFunds() []*FundResponse {
	if x != nil {
		return x.Funds
	}
	return nil
}

type InvestFundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FundId          int64                  `protobuf:"varint,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	ClientId        int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientType      string                 `protobuf:"bytes,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"` // "CLIENT" or "BANK"
	SourceAccountId int64                  `protobuf:"varint,4,opt,name=source_account_id,json=sourceAccountId,proto3" json:"source_account_id,omitempty"`
	Amount          float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InvestFundRequest) Reset() {
	*x = InvestFundRequest{}
	mi := &file_fund_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestFundRequest) ProtoMessage() {}

func (x *InvestFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestFundRequest.ProtoReflect.Descriptor instead.
func (*InvestFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{10}
}

func (x *InvestFundRequest) GetFundId() int64 {
	if x != nil {
		return x.FundId
	}
	return 0
}

func (x *InvestFundRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *InvestFundRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *InvestFundRequest) GetSourceAccountId() int64 {
	if x != nil {
		return x.SourceAccountId
	}
	return 0
}

func (x *InvestFundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawFundRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	FundId               int64                  `protobuf:"varint,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	ClientId             int64                  `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientType           string                 `protobuf:"bytes,3,opt,name=client_type,json=clientType,proto3" json:"client_type,omitempty"`
	DestinationAccountId int64                  `protobuf:"varint,4,opt,name=destination_account_id,json=destinationAccountId,proto3" json:"destination_account_id,omitempty"`
	Amount               float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"` // 0 = full position
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *WithdrawFundRequest) Reset() {
	*x = WithdrawFundRequest{}
	mi := &file_fund_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawFundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawFundRequest) ProtoMessage() {}

func (x *WithdrawFundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawFundRequest.ProtoReflect.Descriptor instead.
func (*WithdrawFundRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{11}
}

func (x *WithdrawFundRequest) GetFundId() int64 {
	if x != nil {
		return x.FundId
	}
	return 0
}

func (x *WithdrawFundRequest) GetClientId() int64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *WithdrawFundRequest) GetClientType() string {
	if x != nil {
		return x.ClientType
	}
	return ""
}

func (x *WithdrawFundRequest) GetDestinationAccountId() int64 {
	if x != nil {
		return x.DestinationAccountId
	}
	return 0
}

func (x *WithdrawFundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BankFundPosition struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FundId           int64                  `protobuf:"varint,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	FundName         string                 `protobuf:"bytes,2,opt,name=fund_name,json=fundName,proto3" json:"fund_name,omitempty"`
	ManagerName      string                 `protobuf:"bytes,3,opt,name=manager_name,json=managerName,proto3" json:"manager_name,omitempty"`
	BankSharePercent float64                `protobuf:"fixed64,4,opt,name=bank_share_percent,json=bankSharePercent,proto3" json:"bank_share_percent,omitempty"`
	BankShareRsd     float64                `protobuf:"fixed64,5,opt,name=bank_share_rsd,json=bankShareRsd,proto3" json:"bank_share_rsd,omitempty"`
	ProfitRsd        float64                `protobuf:"fixed64,6,opt,name=profit_rsd,json=profitRsd,proto3" json:"profit_rsd,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *BankFundPosition) Reset() {
	*x = BankFundPosition{}
	mi := &file_fund_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankFundPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankFundPosition) ProtoMessage() {}

func (x *BankFundPosition) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankFundPosition.ProtoReflect.Descriptor instead.
func (*BankFundPosition) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{12}
}

func (x *BankFundPosition) GetFundId() int64 {
	if x != nil {
		return x.FundId
	}
	return 0
}

func (x *BankFundPosition) GetFundName() string {
	if x != nil {
		return x.FundName
	}
	return ""
}

func (x *BankFundPosition) GetManagerName() string {
	if x != nil {
		return x.ManagerName
	}
	return ""
}

func (x *BankFundPosition) GetBankSharePercent() float64 {
	if x != nil {
		return x.BankSharePercent
	}
	return 0
}

func (x *BankFundPosition) GetBankShareRsd() float64 {
	if x != nil {
		return x.BankShareRsd
	}
	return 0
}

func (x *BankFundPosition) GetProfitRsd() float64 {
	if x != nil {
		return x.ProfitRsd
	}
	return 0
}

type GetBankPositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankPositionsRequest) Reset() {
	*x = GetBankPositionsRequest{}
	mi := &file_fund_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankPositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankPositionsRequest) ProtoMessage() {}

func (x *GetBankPositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankPositionsRequest.ProtoReflect.Descriptor instead.
func (*GetBankPositionsRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{13}
}

type GetBankPositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Positions     []*BankFundPosition    `protobuf:"bytes,1,rep,name=positions,proto3" json:"positions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBankPositionsResponse) Reset() {
	*x = GetBankPositionsResponse{}
	mi := &file_fund_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBankPositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBankPositionsResponse) ProtoMessage() {}

func (x *GetBankPositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBankPositionsResponse.ProtoReflect.Descriptor instead.
func (*GetBankPositionsResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{14}
}

func (x *GetBankPositionsResponse) GetPositions() []*BankFundPosition {
	if x != nil {
		return x.Positions
	}
	return nil
}

type ValidateFundAccountRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FundId         int64                  `protobuf:"varint,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	ManagerId      int64                  `protobuf:"varint,2,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	RequiredAmount float64                `protobuf:"fixed64,3,opt,name=required_amount,json=requiredAmount,proto3" json:"required_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ValidateFundAccountRequest) Reset() {
	*x = ValidateFundAccountRequest{}
	mi := &file_fund_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFundAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFundAccountRequest) ProtoMessage() {}

func (x *ValidateFundAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFundAccountRequest.ProtoReflect.Descriptor instead.
func (*ValidateFundAccountRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{15}
}

func (x *ValidateFundAccountRequest) GetFundId() int64 {
	if x != nil {
		return x.FundId
	}
	return 0
}

func (x *ValidateFundAccountRequest) GetManagerId() int64 {
	if x != nil {
		return x.ManagerId
	}
	return 0
}

func (x *ValidateFundAccountRequest) GetRequiredAmount() float64 {
	if x != nil {
		return x.RequiredAmount
	}
	return 0
}

type ValidateFundAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     int64                  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IsLiquid      bool                   `protobuf:"varint,2,opt,name=is_liquid,json=isLiquid,proto3" json:"is_liquid,omitempty"`
	LiquidAssets  float64                `protobuf:"fixed64,3,opt,name=liquid_assets,json=liquidAssets,proto3" json:"liquid_assets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateFundAccountResponse) Reset() {
	*x = ValidateFundAccountResponse{}
	mi := &file_fund_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateFundAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateFundAccountResponse) ProtoMessage() {}

func (x *ValidateFundAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateFundAccountResponse.ProtoReflect.Descriptor instead.
func (*ValidateFundAccountResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateFundAccountResponse) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *ValidateFundAccountResponse) GetIsLiquid() bool {
	if x != nil {
		return x.IsLiquid
	}
	return false
}

func (x *ValidateFundAccountResponse) GetLiquidAssets() float64 {
	if x != nil {
		return x.LiquidAssets
	}
	return 0
}

type UpdateFundHoldingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FundId        int64                  `protobuf:"varint,1,opt,name=fund_id,json=fundId,proto3" json:"fund_id,omitempty"`
	ListingId     int64                  `protobuf:"varint,2,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Quantity      int64                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Direction     string                 `protobuf:"bytes,5,opt,name=direction,proto3" json:"direction,omitempty"` // BUY or SELL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFundHoldingRequest) Reset() {
	*x = UpdateFundHoldingRequest{}
	mi := &file_fund_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFundHoldingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFundHoldingRequest) ProtoMessage() {}

func (x *UpdateFundHoldingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFundHoldingRequest.ProtoReflect.Descriptor instead.
func (*UpdateFundHoldingRequest) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateFundHoldingRequest) GetFundId() int64 {
	if x != nil {
		return x.FundId
	}
	return 0
}

func (x *UpdateFundHoldingRequest) GetListingId() int64 {
	if x != nil {
		return x.ListingId
	}
	return 0
}

func (x *UpdateFundHoldingRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *UpdateFundHoldingRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateFundHoldingRequest) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

type UpdateFundHoldingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFundHoldingResponse) Reset() {
	*x = UpdateFundHoldingResponse{}
	mi := &file_fund_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFundHoldingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFundHoldingResponse) ProtoMessage() {}

func (x *UpdateFundHoldingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fund_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFundHoldingResponse.ProtoReflect.Descriptor instead.
func (*UpdateFundHoldingResponse) Descriptor() ([]byte, []int) {
	return file_fund_proto_rawDescGZIP(), []int{18}
}

var File_fund_proto protoreflect.FileDescriptor

const file_fund_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"fund.proto\x12\x04fund\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xbf\x01\n" +
	"\x11CreateFundRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x03 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x04 \x01(\x03R\tmanagerId\x12\"\n" +
	"\rcreated_by_id\x18\x05 \x01(\x03R\vcreatedById\"\xab\x01\n" +
	"\x11UpdateFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x04 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\x03R\tmanagerId\"#\n" +
	"\x11DeleteFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x14\n" +
	"\x12DeleteFundResponse\">\n" +
	"\x10ListFundsRequest\x12*\n" +
	"\x11manager_id_filter\x18\x01 \x01(\x03R\x0fmanagerIdFilter\" \n" +
	"\x0eGetFundRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xa2\x03\n" +
	"\fFundResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x121\n" +
	"\x14minimum_contribution\x18\x04 \x01(\x01R\x13minimumContribution\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\x03R\tmanagerId\x12!\n" +
	"\fmanager_name\x18\x06 \x01(\tR\vmanagerName\x12#\n" +
	"\rliquid_assets\x18\a \x01(\x01R\fliquidAssets\x12\x1d\n" +
	"\n" +
	"fund_value\x18\b \x01(\x01R\tfundValue\x12\x16\n" +
	"\x06profit\x18\t \x01(\x01R\x06profit\x12%\n" +
	"\x0eaccount_number\x18\n" +
	" \x01(\tR\raccountNumber\x12\x1d\n" +
	"\n" +
	"created_at\x18\v \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06active\x18\f \x01(\bR\x06active\x12\x1d\n" +
	"\n" +
	"account_id\x18\r \x01(\x03R\taccountId\"=\n" +
	"\x11ListFundsResponse\x12(\n" +
	"\x05funds\x18\x01 \x03(\v2\x12.fund.FundResponseR\x05funds\"\xae\x01\n" +
	"\x11InvestFundRequest\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\x03R\x06fundId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\tR\n" +
	"clientType\x12*\n" +
	"\x11source_account_id\x18\x04 \x01(\x03R\x0fsourceAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\"\xba\x01\n" +
	"\x13WithdrawFundRequest\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\x03R\x06fundId\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x03R\bclientId\x12\x1f\n" +
	"\vclient_type\x18\x03 \x01(\tR\n" +
	"clientType\x124\n" +
	"\x16destination_account_id\x18\x04 \x01(\x03R\x14destinationAccountId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amount\"\xde\x01\n" +
	"\x10BankFundPosition\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\x03R\x06fundId\x12\x1b\n" +
	"\tfund_name\x18\x02 \x01(\tR\bfundName\x12!\n" +
	"\fmanager_name\x18\x03 \x01(\tR\vmanagerName\x12,\n" +
	"\x12bank_share_percent\x18\x04 \x01(\x01R\x10bankSharePercent\x12$\n" +
	"\x0ebank_share_rsd\x18\x05 \x01(\x01R\fbankShareRsd\x12\x1d\n" +
	"\n" +
	"profit_rsd\x18\x06 \x01(\x01R\tprofitRsd\"\x19\n" +
	"\x17GetBankPositionsRequest\"P\n" +
	"\x18GetBankPositionsResponse\x124\n" +
	"\tpositions\x18\x01 \x03(\v2\x16.fund.BankFundPositionR\tpositions\"}\n" +
	"\x1aValidateFundAccountRequest\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\x03R\x06fundId\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x02 \x01(\x03R\tmanagerId\x12'\n" +
	"\x0frequired_amount\x18\x03 \x01(\x01R\x0erequiredAmount\"~\n" +
	"\x1bValidateFundAccountResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\x03R\taccountId\x12\x1b\n" +
	"\tis_liquid\x18\x02 \x01(\bR\bisLiquid\x12#\n" +
	"\rliquid_assets\x18\x03 \x01(\x01R\fliquidAssets\"\xa2\x01\n" +
	"\x18UpdateFundHoldingRequest\x12\x17\n" +
	"\afund_id\x18\x01 \x01(\x03R\x06fundId\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x02 \x01(\x03R\tlistingId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x03R\bquantity\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tdirection\x18\x05 \x01(\tR\tdirection\"\x1b\n" +
	"\x19UpdateFundHoldingResponse2\xe5\x05\n" +
	"\vFundService\x12-\n" +
	"\x04Ping\x12\x11.fund.PingRequest\x1a\x12.fund.PingResponse\x129\n" +
	"\n" +
	"CreateFund\x12\x17.fund.CreateFundRequest\x1a\x12.fund.FundResponse\x12<\n" +
	"\tListFunds\x12\x16.fund.ListFundsRequest\x1a\x17.fund.ListFundsResponse\x123\n" +
	"\aGetFund\x12\x14.fund.GetFundRequest\x1a\x12.fund.FundResponse\x129\n" +
	"\n" +
	"UpdateFund\x12\x17.fund.UpdateFundRequest\x1a\x12.fund.FundResponse\x12?\n" +
	"\n" +
	"DeleteFund\x12\x17.fund.DeleteFundRequest\x1a\x18.fund.DeleteFundResponse\x129\n" +
	"\n" +
	"InvestFund\x12\x17.fund.InvestFundRequest\x1a\x12.fund.FundResponse\x12=\n" +
	"\fWithdrawFund\x12\x19.fund.WithdrawFundRequest\x1a\x12.fund.FundResponse\x12Q\n" +
	"\x10GetBankPositions\x12\x1d.fund.GetBankPositionsRequest\x1a\x1e.fund.GetBankPositionsResponse\x12Z\n" +
	"\x13ValidateFundAccount\x12 .fund.ValidateFundAccountRequest\x1a!.fund.ValidateFundAccountResponse\x12T\n" +
	"\x11UpdateFundHolding\x12\x1e.fund.UpdateFundHoldingRequest\x1a\x1f.fund.UpdateFundHoldingResponseB9Z7github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/fundb\x06proto3"

var (
	file_fund_proto_rawDescOnce sync.Once
	file_fund_proto_rawDescData []byte
)

func file_fund_proto_rawDescGZIP() []byte {
	file_fund_proto_rawDescOnce.Do(func() {
		file_fund_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)))
	})
	return file_fund_proto_rawDescData
}

var file_fund_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_fund_proto_goTypes = []any{
	(*PingRequest)(nil),                 // 0: fund.PingRequest
	(*PingResponse)(nil),                // 1: fund.PingResponse
	(*CreateFundRequest)(nil),           // 2: fund.CreateFundRequest
	(*UpdateFundRequest)(nil),           // 3: fund.UpdateFundRequest
	(*DeleteFundRequest)(nil),           // 4: fund.DeleteFundRequest
	(*DeleteFundResponse)(nil),          // 5: fund.DeleteFundResponse
	(*ListFundsRequest)(nil),            // 6: fund.ListFundsRequest
	(*GetFundRequest)(nil),              // 7: fund.GetFundRequest
	(*FundResponse)(nil),                // 8: fund.FundResponse
	(*ListFundsResponse)(nil),           // 9: fund.ListFundsResponse
	(*InvestFundRequest)(nil),           // 10: fund.InvestFundRequest
	(*WithdrawFundRequest)(nil),         // 11: fund.WithdrawFundRequest
	(*BankFundPosition)(nil),            // 12: fund.BankFundPosition
	(*GetBankPositionsRequest)(nil),     // 13: fund.GetBankPositionsRequest
	(*GetBankPositionsResponse)(nil),    // 14: fund.GetBankPositionsResponse
	(*ValidateFundAccountRequest)(nil),  // 15: fund.ValidateFundAccountRequest
	(*ValidateFundAccountResponse)(nil), // 16: fund.ValidateFundAccountResponse
	(*UpdateFundHoldingRequest)(nil),    // 17: fund.UpdateFundHoldingRequest
	(*UpdateFundHoldingResponse)(nil),   // 18: fund.UpdateFundHoldingResponse
}
var file_fund_proto_depIdxs = []int32{
	8,  // 0: fund.ListFundsResponse.funds:type_name -> fund.FundResponse
	12, // 1: fund.GetBankPositionsResponse.positions:type_name -> fund.BankFundPosition
	0,  // 2: fund.FundService.Ping:input_type -> fund.PingRequest
	2,  // 3: fund.FundService.CreateFund:input_type -> fund.CreateFundRequest
	6,  // 4: fund.FundService.ListFunds:input_type -> fund.ListFundsRequest
	7,  // 5: fund.FundService.GetFund:input_type -> fund.GetFundRequest
	3,  // 6: fund.FundService.UpdateFund:input_type -> fund.UpdateFundRequest
	4,  // 7: fund.FundService.DeleteFund:input_type -> fund.DeleteFundRequest
	10, // 8: fund.FundService.InvestFund:input_type -> fund.InvestFundRequest
	11, // 9: fund.FundService.WithdrawFund:input_type -> fund.WithdrawFundRequest
	13, // 10: fund.FundService.GetBankPositions:input_type -> fund.GetBankPositionsRequest
	15, // 11: fund.FundService.ValidateFundAccount:input_type -> fund.ValidateFundAccountRequest
	17, // 12: fund.FundService.UpdateFundHolding:input_type -> fund.UpdateFundHoldingRequest
	1,  // 13: fund.FundService.Ping:output_type -> fund.PingResponse
	8,  // 14: fund.FundService.CreateFund:output_type -> fund.FundResponse
	9,  // 15: fund.FundService.ListFunds:output_type -> fund.ListFundsResponse
	8,  // 16: fund.FundService.GetFund:output_type -> fund.FundResponse
	8,  // 17: fund.FundService.UpdateFund:output_type -> fund.FundResponse
	5,  // 18: fund.FundService.DeleteFund:output_type -> fund.DeleteFundResponse
	8,  // 19: fund.FundService.InvestFund:output_type -> fund.FundResponse
	8,  // 20: fund.FundService.WithdrawFund:output_type -> fund.FundResponse
	14, // 21: fund.FundService.GetBankPositions:output_type -> fund.GetBankPositionsResponse
	16, // 22: fund.FundService.ValidateFundAccount:output_type -> fund.ValidateFundAccountResponse
	18, // 23: fund.FundService.UpdateFundHolding:output_type -> fund.UpdateFundHoldingResponse
	13, // [13:24] is the sub-list for method output_type
	2,  // [2:13] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_fund_proto_init() }
func file_fund_proto_init() {
	if File_fund_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fund_proto_rawDesc), len(file_fund_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fund_proto_goTypes,
		DependencyIndexes: file_fund_proto_depIdxs,
		MessageInfos:      file_fund_proto_msgTypes,
	}.Build()
	File_fund_proto = out.File
	file_fund_proto_goTypes = nil
	file_fund_proto_depIdxs = nil
}
