// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: otc.proto

package otc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_otc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_otc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateNegotiationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BuyerId        int64                  `protobuf:"varint,1,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	BuyerType      string                 `protobuf:"bytes,2,opt,name=buyer_type,json=buyerType,proto3" json:"buyer_type,omitempty"` // CLIENT or EMPLOYEE
	SellerId       int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	SellerType     string                 `protobuf:"bytes,4,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"` // CLIENT or EMPLOYEE
	Ticker         string                 `protobuf:"bytes,5,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Amount         int32                  `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	PricePerStock  float64                `protobuf:"fixed64,7,opt,name=price_per_stock,json=pricePerStock,proto3" json:"price_per_stock,omitempty"`
	SettlementDate string                 `protobuf:"bytes,8,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"` // YYYY-MM-DD
	Premium        float64                `protobuf:"fixed64,9,opt,name=premium,proto3" json:"premium,omitempty"`
	Currency       string                 `protobuf:"bytes,10,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateNegotiationRequest) Reset() {
	*x = CreateNegotiationRequest{}
	mi := &file_otc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNegotiationRequest) ProtoMessage() {}

func (x *CreateNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNegotiationRequest.ProtoReflect.Descriptor instead.
func (*CreateNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNegotiationRequest) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *CreateNegotiationRequest) GetBuyerType() string {
	if x != nil {
		return x.BuyerType
	}
	return ""
}

func (x *CreateNegotiationRequest) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *CreateNegotiationRequest) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *CreateNegotiationRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *CreateNegotiationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateNegotiationRequest) GetPricePerStock() float64 {
	if x != nil {
		return x.PricePerStock
	}
	return 0
}

func (x *CreateNegotiationRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *CreateNegotiationRequest) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *CreateNegotiationRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CounterOfferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NegotiationId  int64                  `protobuf:"varint,1,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	CallerId       int64                  `protobuf:"varint,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType     string                 `protobuf:"bytes,3,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"` // CLIENT or EMPLOYEE
	Amount         int32                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	PricePerStock  float64                `protobuf:"fixed64,5,opt,name=price_per_stock,json=pricePerStock,proto3" json:"price_per_stock,omitempty"`
	SettlementDate string                 `protobuf:"bytes,6,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	Premium        float64                `protobuf:"fixed64,7,opt,name=premium,proto3" json:"premium,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CounterOfferRequest) Reset() {
	*x = CounterOfferRequest{}
	mi := &file_otc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CounterOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CounterOfferRequest) ProtoMessage() {}

func (x *CounterOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CounterOfferRequest.ProtoReflect.Descriptor instead.
func (*CounterOfferRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{3}
}

func (x *CounterOfferRequest) GetNegotiationId() int64 {
	if x != nil {
		return x.NegotiationId
	}
	return 0
}

func (x *CounterOfferRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *CounterOfferRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

func (x *CounterOfferRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CounterOfferRequest) GetPricePerStock() float64 {
	if x != nil {
		return x.PricePerStock
	}
	return 0
}

func (x *CounterOfferRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *CounterOfferRequest) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

type AcceptNegotiationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NegotiationId  int64                  `protobuf:"varint,1,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	CallerId       int64                  `protobuf:"varint,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType     string                 `protobuf:"bytes,3,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"`
	BuyerAccountId int64                  `protobuf:"varint,4,opt,name=buyer_account_id,json=buyerAccountId,proto3" json:"buyer_account_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcceptNegotiationRequest) Reset() {
	*x = AcceptNegotiationRequest{}
	mi := &file_otc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptNegotiationRequest) ProtoMessage() {}

func (x *AcceptNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptNegotiationRequest.ProtoReflect.Descriptor instead.
func (*AcceptNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptNegotiationRequest) GetNegotiationId() int64 {
	if x != nil {
		return x.NegotiationId
	}
	return 0
}

func (x *AcceptNegotiationRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *AcceptNegotiationRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

func (x *AcceptNegotiationRequest) GetBuyerAccountId() int64 {
	if x != nil {
		return x.BuyerAccountId
	}
	return 0
}

type RejectNegotiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NegotiationId int64                  `protobuf:"varint,1,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	CallerId      int64                  `protobuf:"varint,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType    string                 `protobuf:"bytes,3,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectNegotiationRequest) Reset() {
	*x = RejectNegotiationRequest{}
	mi := &file_otc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectNegotiationRequest) ProtoMessage() {}

func (x *RejectNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectNegotiationRequest.ProtoReflect.Descriptor instead.
func (*RejectNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{5}
}

func (x *RejectNegotiationRequest) GetNegotiationId() int64 {
	if x != nil {
		return x.NegotiationId
	}
	return 0
}

func (x *RejectNegotiationRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *RejectNegotiationRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

type ListNegotiationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      int64                  `protobuf:"varint,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType    string                 `protobuf:"bytes,2,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"` // CLIENT or EMPLOYEE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNegotiationsRequest) Reset() {
	*x = ListNegotiationsRequest{}
	mi := &file_otc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNegotiationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNegotiationsRequest) ProtoMessage() {}

func (x *ListNegotiationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNegotiationsRequest.ProtoReflect.Descriptor instead.
func (*ListNegotiationsRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{6}
}

func (x *ListNegotiationsRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ListNegotiationsRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

type GetNegotiationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NegotiationId int64                  `protobuf:"varint,1,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNegotiationRequest) Reset() {
	*x = GetNegotiationRequest{}
	mi := &file_otc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNegotiationRequest) ProtoMessage() {}

func (x *GetNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNegotiationRequest.ProtoReflect.Descriptor instead.
func (*GetNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{7}
}

func (x *GetNegotiationRequest) GetNegotiationId() int64 {
	if x != nil {
		return x.NegotiationId
	}
	return 0
}

type NegotiationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ticker         string                 `protobuf:"bytes,2,opt,name=ticker,proto3" json:"ticker,omitempty"`
	SellerId       int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	SellerType     string                 `protobuf:"bytes,4,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	SellerName     string                 `protobuf:"bytes,5,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	BuyerId        int64                  `protobuf:"varint,6,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	BuyerType      string                 `protobuf:"bytes,7,opt,name=buyer_type,json=buyerType,proto3" json:"buyer_type,omitempty"`
	BuyerName      string                 `protobuf:"bytes,8,opt,name=buyer_name,json=buyerName,proto3" json:"buyer_name,omitempty"`
	Amount         int32                  `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	PricePerStock  float64                `protobuf:"fixed64,10,opt,name=price_per_stock,json=pricePerStock,proto3" json:"price_per_stock,omitempty"`
	SettlementDate string                 `protobuf:"bytes,11,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	Premium        float64                `protobuf:"fixed64,12,opt,name=premium,proto3" json:"premium,omitempty"`
	Currency       string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	LastModified   string                 `protobuf:"bytes,14,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"` // RFC3339
	ModifiedById   int64                  `protobuf:"varint,15,opt,name=modified_by_id,json=modifiedById,proto3" json:"modified_by_id,omitempty"`
	ModifiedByType string                 `protobuf:"bytes,16,opt,name=modified_by_type,json=modifiedByType,proto3" json:"modified_by_type,omitempty"`
	ModifiedByName string                 `protobuf:"bytes,17,opt,name=modified_by_name,json=modifiedByName,proto3" json:"modified_by_name,omitempty"`
	Status         string                 `protobuf:"bytes,18,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NegotiationResponse) Reset() {
	*x = NegotiationResponse{}
	mi := &file_otc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiationResponse) ProtoMessage() {}

func (x *NegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiationResponse.ProtoReflect.Descriptor instead.
func (*NegotiationResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{8}
}

func (x *NegotiationResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NegotiationResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *NegotiationResponse) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *NegotiationResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *NegotiationResponse) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *NegotiationResponse) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *NegotiationResponse) GetBuyerType() string {
	if x != nil {
		return x.BuyerType
	}
	return ""
}

func (x *NegotiationResponse) GetBuyerName() string {
	if x != nil {
		return x.BuyerName
	}
	return ""
}

func (x *NegotiationResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *NegotiationResponse) GetPricePerStock() float64 {
	if x != nil {
		return x.PricePerStock
	}
	return 0
}

func (x *NegotiationResponse) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *NegotiationResponse) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *NegotiationResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *NegotiationResponse) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *NegotiationResponse) GetModifiedById() int64 {
	if x != nil {
		return x.ModifiedById
	}
	return 0
}

func (x *NegotiationResponse) GetModifiedByType() string {
	if x != nil {
		return x.ModifiedByType
	}
	return ""
}

func (x *NegotiationResponse) GetModifiedByName() string {
	if x != nil {
		return x.ModifiedByName
	}
	return ""
}

func (x *NegotiationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListNegotiationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Negotiations  []*NegotiationResponse `protobuf:"bytes,1,rep,name=negotiations,proto3" json:"negotiations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNegotiationsResponse) Reset() {
	*x = ListNegotiationsResponse{}
	mi := &file_otc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNegotiationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNegotiationsResponse) ProtoMessage() {}

func (x *ListNegotiationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNegotiationsResponse.ProtoReflect.Descriptor instead.
func (*ListNegotiationsResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{9}
}

func (x *ListNegotiationsResponse) GetNegotiations() []*NegotiationResponse {
	if x != nil {
		return x.Negotiations
	}
	return nil
}

type ContractResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	NegotiationId  int64                  `protobuf:"varint,2,opt,name=negotiation_id,json=negotiationId,proto3" json:"negotiation_id,omitempty"`
	SellerId       int64                  `protobuf:"varint,3,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	SellerType     string                 `protobuf:"bytes,4,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"`
	SellerName     string                 `protobuf:"bytes,5,opt,name=seller_name,json=sellerName,proto3" json:"seller_name,omitempty"`
	BuyerId        int64                  `protobuf:"varint,6,opt,name=buyer_id,json=buyerId,proto3" json:"buyer_id,omitempty"`
	BuyerType      string                 `protobuf:"bytes,7,opt,name=buyer_type,json=buyerType,proto3" json:"buyer_type,omitempty"`
	BuyerName      string                 `protobuf:"bytes,8,opt,name=buyer_name,json=buyerName,proto3" json:"buyer_name,omitempty"`
	Ticker         string                 `protobuf:"bytes,9,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Amount         int32                  `protobuf:"varint,10,opt,name=amount,proto3" json:"amount,omitempty"`
	StrikePrice    float64                `protobuf:"fixed64,11,opt,name=strike_price,json=strikePrice,proto3" json:"strike_price,omitempty"`
	Premium        float64                `protobuf:"fixed64,12,opt,name=premium,proto3" json:"premium,omitempty"`
	Currency       string                 `protobuf:"bytes,13,opt,name=currency,proto3" json:"currency,omitempty"`
	SettlementDate string                 `protobuf:"bytes,14,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	Status         string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Profit         float64                `protobuf:"fixed64,17,opt,name=profit,proto3" json:"profit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractResponse) Reset() {
	*x = ContractResponse{}
	mi := &file_otc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractResponse) ProtoMessage() {}

func (x *ContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractResponse.ProtoReflect.Descriptor instead.
func (*ContractResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{10}
}

func (x *ContractResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ContractResponse) GetNegotiationId() int64 {
	if x != nil {
		return x.NegotiationId
	}
	return 0
}

func (x *ContractResponse) GetSellerId() int64 {
	if x != nil {
		return x.SellerId
	}
	return 0
}

func (x *ContractResponse) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

func (x *ContractResponse) GetSellerName() string {
	if x != nil {
		return x.SellerName
	}
	return ""
}

func (x *ContractResponse) GetBuyerId() int64 {
	if x != nil {
		return x.BuyerId
	}
	return 0
}

func (x *ContractResponse) GetBuyerType() string {
	if x != nil {
		return x.BuyerType
	}
	return ""
}

func (x *ContractResponse) GetBuyerName() string {
	if x != nil {
		return x.BuyerName
	}
	return ""
}

func (x *ContractResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *ContractResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ContractResponse) GetStrikePrice() float64 {
	if x != nil {
		return x.StrikePrice
	}
	return 0
}

func (x *ContractResponse) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *ContractResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ContractResponse) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *ContractResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContractResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ContractResponse) GetProfit() float64 {
	if x != nil {
		return x.Profit
	}
	return 0
}

type ListContractsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      int64                  `protobuf:"varint,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType    string                 `protobuf:"bytes,2,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"`
	StatusFilter  string                 `protobuf:"bytes,3,opt,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsRequest) Reset() {
	*x = ListContractsRequest{}
	mi := &file_otc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsRequest) ProtoMessage() {}

func (x *ListContractsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsRequest.ProtoReflect.Descriptor instead.
func (*ListContractsRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{11}
}

func (x *ListContractsRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ListContractsRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

func (x *ListContractsRequest) GetStatusFilter() string {
	if x != nil {
		return x.StatusFilter
	}
	return ""
}

type ListContractsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contracts     []*ContractResponse    `protobuf:"bytes,1,rep,name=contracts,proto3" json:"contracts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractsResponse) Reset() {
	*x = ListContractsResponse{}
	mi := &file_otc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractsResponse) ProtoMessage() {}

func (x *ListContractsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractsResponse.ProtoReflect.Descriptor instead.
func (*ListContractsResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{12}
}

func (x *ListContractsResponse) GetContracts() []*ContractResponse {
	if x != nil {
		return x.Contracts
	}
	return nil
}

type ExerciseContractRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ContractId     int64                  `protobuf:"varint,1,opt,name=contract_id,json=contractId,proto3" json:"contract_id,omitempty"`
	CallerId       int64                  `protobuf:"varint,2,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType     string                 `protobuf:"bytes,3,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"`
	BuyerAccountId int64                  `protobuf:"varint,4,opt,name=buyer_account_id,json=buyerAccountId,proto3" json:"buyer_account_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExerciseContractRequest) Reset() {
	*x = ExerciseContractRequest{}
	mi := &file_otc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseContractRequest) ProtoMessage() {}

func (x *ExerciseContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseContractRequest.ProtoReflect.Descriptor instead.
func (*ExerciseContractRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{13}
}

func (x *ExerciseContractRequest) GetContractId() int64 {
	if x != nil {
		return x.ContractId
	}
	return 0
}

func (x *ExerciseContractRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *ExerciseContractRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

func (x *ExerciseContractRequest) GetBuyerAccountId() int64 {
	if x != nil {
		return x.BuyerAccountId
	}
	return 0
}

type ExerciseContractResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ExecutedAt    string                 `protobuf:"bytes,2,opt,name=executed_at,json=executedAt,proto3" json:"executed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExerciseContractResponse) Reset() {
	*x = ExerciseContractResponse{}
	mi := &file_otc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExerciseContractResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExerciseContractResponse) ProtoMessage() {}

func (x *ExerciseContractResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExerciseContractResponse.ProtoReflect.Descriptor instead.
func (*ExerciseContractResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{14}
}

func (x *ExerciseContractResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExerciseContractResponse) GetExecutedAt() string {
	if x != nil {
		return x.ExecutedAt
	}
	return ""
}

type GetMarketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallerId      int64                  `protobuf:"varint,1,opt,name=caller_id,json=callerId,proto3" json:"caller_id,omitempty"`
	CallerType    string                 `protobuf:"bytes,2,opt,name=caller_type,json=callerType,proto3" json:"caller_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketRequest) Reset() {
	*x = GetMarketRequest{}
	mi := &file_otc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketRequest) ProtoMessage() {}

func (x *GetMarketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketRequest.ProtoReflect.Descriptor instead.
func (*GetMarketRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{15}
}

func (x *GetMarketRequest) GetCallerId() int64 {
	if x != nil {
		return x.CallerId
	}
	return 0
}

func (x *GetMarketRequest) GetCallerType() string {
	if x != nil {
		return x.CallerType
	}
	return ""
}

type MarketItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ticker        string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Amount        int32                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	PricePerStock float64                `protobuf:"fixed64,4,opt,name=price_per_stock,json=pricePerStock,proto3" json:"price_per_stock,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	LastUpdated   string                 `protobuf:"bytes,6,opt,name=last_updated,json=lastUpdated,proto3" json:"last_updated,omitempty"`
	OwnerName     string                 `protobuf:"bytes,7,opt,name=owner_name,json=ownerName,proto3" json:"owner_name,omitempty"`
	OwnerBank     string                 `protobuf:"bytes,8,opt,name=owner_bank,json=ownerBank,proto3" json:"owner_bank,omitempty"`
	OwnerId       int64                  `protobuf:"varint,9,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType     string                 `protobuf:"bytes,10,opt,name=owner_type,json=ownerType,proto3" json:"owner_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketItem) Reset() {
	*x = MarketItem{}
	mi := &file_otc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketItem) ProtoMessage() {}

func (x *MarketItem) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketItem.ProtoReflect.Descriptor instead.
func (*MarketItem) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{16}
}

func (x *MarketItem) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *MarketItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MarketItem) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *MarketItem) GetPricePerStock() float64 {
	if x != nil {
		return x.PricePerStock
	}
	return 0
}

func (x *MarketItem) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *MarketItem) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

func (x *MarketItem) GetOwnerName() string {
	if x != nil {
		return x.OwnerName
	}
	return ""
}

func (x *MarketItem) GetOwnerBank() string {
	if x != nil {
		return x.OwnerBank
	}
	return ""
}

func (x *MarketItem) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *MarketItem) GetOwnerType() string {
	if x != nil {
		return x.OwnerType
	}
	return ""
}

type GetMarketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MarketItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMarketResponse) Reset() {
	*x = GetMarketResponse{}
	mi := &file_otc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMarketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMarketResponse) ProtoMessage() {}

func (x *GetMarketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMarketResponse.ProtoReflect.Descriptor instead.
func (*GetMarketResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{17}
}

func (x *GetMarketResponse) GetItems() []*MarketItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OtcEmptyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtcEmptyResponse) Reset() {
	*x = OtcEmptyResponse{}
	mi := &file_otc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtcEmptyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtcEmptyResponse) ProtoMessage() {}

func (x *OtcEmptyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtcEmptyResponse.ProtoReflect.Descriptor instead.
func (*OtcEmptyResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{18}
}

type CreateInterbankNegotiationRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Ticker               string                 `protobuf:"bytes,1,opt,name=ticker,proto3" json:"ticker,omitempty"`
	SettlementDate       string                 `protobuf:"bytes,2,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	PricePerUnit         float64                `protobuf:"fixed64,3,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	PriceCurrency        string                 `protobuf:"bytes,4,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	Premium              float64                `protobuf:"fixed64,5,opt,name=premium,proto3" json:"premium,omitempty"`
	BuyerRoutingNumber   int32                  `protobuf:"varint,6,opt,name=buyer_routing_number,json=buyerRoutingNumber,proto3" json:"buyer_routing_number,omitempty"`
	BuyerExternalId      string                 `protobuf:"bytes,7,opt,name=buyer_external_id,json=buyerExternalId,proto3" json:"buyer_external_id,omitempty"`
	SellerRoutingNumber  int32                  `protobuf:"varint,8,opt,name=seller_routing_number,json=sellerRoutingNumber,proto3" json:"seller_routing_number,omitempty"`
	SellerExternalId     string                 `protobuf:"bytes,9,opt,name=seller_external_id,json=sellerExternalId,proto3" json:"seller_external_id,omitempty"`
	CreatorRoutingNumber int32                  `protobuf:"varint,10,opt,name=creator_routing_number,json=creatorRoutingNumber,proto3" json:"creator_routing_number,omitempty"`
	CreatorExternalId    string                 `protobuf:"bytes,11,opt,name=creator_external_id,json=creatorExternalId,proto3" json:"creator_external_id,omitempty"`
	Amount               int32                  `protobuf:"varint,12,opt,name=amount,proto3" json:"amount,omitempty"`
	SellerType           string                 `protobuf:"bytes,13,opt,name=seller_type,json=sellerType,proto3" json:"seller_type,omitempty"` // CLIENT or EMPLOYEE; defaults to CLIENT if empty
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateInterbankNegotiationRequest) Reset() {
	*x = CreateInterbankNegotiationRequest{}
	mi := &file_otc_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInterbankNegotiationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInterbankNegotiationRequest) ProtoMessage() {}

func (x *CreateInterbankNegotiationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInterbankNegotiationRequest.ProtoReflect.Descriptor instead.
func (*CreateInterbankNegotiationRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{19}
}

func (x *CreateInterbankNegotiationRequest) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetPriceCurrency() string {
	if x != nil {
		return x.PriceCurrency
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetBuyerRoutingNumber() int32 {
	if x != nil {
		return x.BuyerRoutingNumber
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetBuyerExternalId() string {
	if x != nil {
		return x.BuyerExternalId
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetSellerRoutingNumber() int32 {
	if x != nil {
		return x.SellerRoutingNumber
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetSellerExternalId() string {
	if x != nil {
		return x.SellerExternalId
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetCreatorRoutingNumber() int32 {
	if x != nil {
		return x.CreatorRoutingNumber
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetCreatorExternalId() string {
	if x != nil {
		return x.CreatorExternalId
	}
	return ""
}

func (x *CreateInterbankNegotiationRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateInterbankNegotiationRequest) GetSellerType() string {
	if x != nil {
		return x.SellerType
	}
	return ""
}

type InterbankNegotiationResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LocalId              int64                  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	CreatorRoutingNumber int32                  `protobuf:"varint,2,opt,name=creator_routing_number,json=creatorRoutingNumber,proto3" json:"creator_routing_number,omitempty"`
	CreatorExternalId    string                 `protobuf:"bytes,3,opt,name=creator_external_id,json=creatorExternalId,proto3" json:"creator_external_id,omitempty"`
	Ticker               string                 `protobuf:"bytes,4,opt,name=ticker,proto3" json:"ticker,omitempty"`
	SettlementDate       string                 `protobuf:"bytes,5,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	PricePerUnit         float64                `protobuf:"fixed64,6,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	PriceCurrency        string                 `protobuf:"bytes,7,opt,name=price_currency,json=priceCurrency,proto3" json:"price_currency,omitempty"`
	Premium              float64                `protobuf:"fixed64,8,opt,name=premium,proto3" json:"premium,omitempty"`
	Amount               int32                  `protobuf:"varint,9,opt,name=amount,proto3" json:"amount,omitempty"`
	IsOngoing            bool                   `protobuf:"varint,10,opt,name=is_ongoing,json=isOngoing,proto3" json:"is_ongoing,omitempty"`
	BuyerRoutingNumber   int32                  `protobuf:"varint,11,opt,name=buyer_routing_number,json=buyerRoutingNumber,proto3" json:"buyer_routing_number,omitempty"`
	BuyerExternalId      string                 `protobuf:"bytes,12,opt,name=buyer_external_id,json=buyerExternalId,proto3" json:"buyer_external_id,omitempty"`
	SellerRoutingNumber  int32                  `protobuf:"varint,13,opt,name=seller_routing_number,json=sellerRoutingNumber,proto3" json:"seller_routing_number,omitempty"`
	SellerExternalId     string                 `protobuf:"bytes,14,opt,name=seller_external_id,json=sellerExternalId,proto3" json:"seller_external_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *InterbankNegotiationResponse) Reset() {
	*x = InterbankNegotiationResponse{}
	mi := &file_otc_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterbankNegotiationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterbankNegotiationResponse) ProtoMessage() {}

func (x *InterbankNegotiationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterbankNegotiationResponse.ProtoReflect.Descriptor instead.
func (*InterbankNegotiationResponse) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{20}
}

func (x *InterbankNegotiationResponse) GetLocalId() int64 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetCreatorRoutingNumber() int32 {
	if x != nil {
		return x.CreatorRoutingNumber
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetCreatorExternalId() string {
	if x != nil {
		return x.CreatorExternalId
	}
	return ""
}

func (x *InterbankNegotiationResponse) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *InterbankNegotiationResponse) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

func (x *InterbankNegotiationResponse) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetPriceCurrency() string {
	if x != nil {
		return x.PriceCurrency
	}
	return ""
}

func (x *InterbankNegotiationResponse) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetIsOngoing() bool {
	if x != nil {
		return x.IsOngoing
	}
	return false
}

func (x *InterbankNegotiationResponse) GetBuyerRoutingNumber() int32 {
	if x != nil {
		return x.BuyerRoutingNumber
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetBuyerExternalId() string {
	if x != nil {
		return x.BuyerExternalId
	}
	return ""
}

func (x *InterbankNegotiationResponse) GetSellerRoutingNumber() int32 {
	if x != nil {
		return x.SellerRoutingNumber
	}
	return 0
}

func (x *InterbankNegotiationResponse) GetSellerExternalId() string {
	if x != nil {
		return x.SellerExternalId
	}
	return ""
}

type InterbankNegotiationIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	ExternalId    string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterbankNegotiationIdRequest) Reset() {
	*x = InterbankNegotiationIdRequest{}
	mi := &file_otc_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterbankNegotiationIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterbankNegotiationIdRequest) ProtoMessage() {}

func (x *InterbankNegotiationIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterbankNegotiationIdRequest.ProtoReflect.Descriptor instead.
func (*InterbankNegotiationIdRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{21}
}

func (x *InterbankNegotiationIdRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *InterbankNegotiationIdRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

type InterbankCounterOfferRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RoutingNumber  int32                  `protobuf:"varint,1,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	ExternalId     string                 `protobuf:"bytes,2,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	PricePerUnit   float64                `protobuf:"fixed64,3,opt,name=price_per_unit,json=pricePerUnit,proto3" json:"price_per_unit,omitempty"`
	Premium        float64                `protobuf:"fixed64,4,opt,name=premium,proto3" json:"premium,omitempty"`
	Amount         int32                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	SettlementDate string                 `protobuf:"bytes,6,opt,name=settlement_date,json=settlementDate,proto3" json:"settlement_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InterbankCounterOfferRequest) Reset() {
	*x = InterbankCounterOfferRequest{}
	mi := &file_otc_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterbankCounterOfferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterbankCounterOfferRequest) ProtoMessage() {}

func (x *InterbankCounterOfferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otc_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterbankCounterOfferRequest.ProtoReflect.Descriptor instead.
func (*InterbankCounterOfferRequest) Descriptor() ([]byte, []int) {
	return file_otc_proto_rawDescGZIP(), []int{22}
}

func (x *InterbankCounterOfferRequest) GetRoutingNumber() int32 {
	if x != nil {
		return x.RoutingNumber
	}
	return 0
}

func (x *InterbankCounterOfferRequest) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *InterbankCounterOfferRequest) GetPricePerUnit() float64 {
	if x != nil {
		return x.PricePerUnit
	}
	return 0
}

func (x *InterbankCounterOfferRequest) GetPremium() float64 {
	if x != nil {
		return x.Premium
	}
	return 0
}

func (x *InterbankCounterOfferRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InterbankCounterOfferRequest) GetSettlementDate() string {
	if x != nil {
		return x.SettlementDate
	}
	return ""
}

var File_otc_proto protoreflect.FileDescriptor

const file_otc_proto_rawDesc = "" +
	"\n" +
	"\totc.proto\x12\x03otc\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc9\x02\n" +
	"\x18CreateNegotiationRequest\x12\x19\n" +
	"\bbuyer_id\x18\x01 \x01(\x03R\abuyerId\x12\x1d\n" +
	"\n" +
	"buyer_type\x18\x02 \x01(\tR\tbuyerType\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12\x1f\n" +
	"\vseller_type\x18\x04 \x01(\tR\n" +
	"sellerType\x12\x16\n" +
	"\x06ticker\x18\x05 \x01(\tR\x06ticker\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x05R\x06amount\x12&\n" +
	"\x0fprice_per_stock\x18\a \x01(\x01R\rpricePerStock\x12'\n" +
	"\x0fsettlement_date\x18\b \x01(\tR\x0esettlementDate\x12\x18\n" +
	"\apremium\x18\t \x01(\x01R\apremium\x12\x1a\n" +
	"\bcurrency\x18\n" +
	" \x01(\tR\bcurrency\"\xfd\x01\n" +
	"\x13CounterOfferRequest\x12%\n" +
	"\x0enegotiation_id\x18\x01 \x01(\x03R\rnegotiationId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x03 \x01(\tR\n" +
	"callerType\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x05R\x06amount\x12&\n" +
	"\x0fprice_per_stock\x18\x05 \x01(\x01R\rpricePerStock\x12'\n" +
	"\x0fsettlement_date\x18\x06 \x01(\tR\x0esettlementDate\x12\x18\n" +
	"\apremium\x18\a \x01(\x01R\apremium\"\xa9\x01\n" +
	"\x18AcceptNegotiationRequest\x12%\n" +
	"\x0enegotiation_id\x18\x01 \x01(\x03R\rnegotiationId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x03 \x01(\tR\n" +
	"callerType\x12(\n" +
	"\x10buyer_account_id\x18\x04 \x01(\x03R\x0ebuyerAccountId\"\x7f\n" +
	"\x18RejectNegotiationRequest\x12%\n" +
	"\x0enegotiation_id\x18\x01 \x01(\x03R\rnegotiationId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x03 \x01(\tR\n" +
	"callerType\"W\n" +
	"\x17ListNegotiationsRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x02 \x01(\tR\n" +
	"callerType\">\n" +
	"\x15GetNegotiationRequest\x12%\n" +
	"\x0enegotiation_id\x18\x01 \x01(\x03R\rnegotiationId\"\xcb\x04\n" +
	"\x13NegotiationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06ticker\x18\x02 \x01(\tR\x06ticker\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12\x1f\n" +
	"\vseller_type\x18\x04 \x01(\tR\n" +
	"sellerType\x12\x1f\n" +
	"\vseller_name\x18\x05 \x01(\tR\n" +
	"sellerName\x12\x19\n" +
	"\bbuyer_id\x18\x06 \x01(\x03R\abuyerId\x12\x1d\n" +
	"\n" +
	"buyer_type\x18\a \x01(\tR\tbuyerType\x12\x1d\n" +
	"\n" +
	"buyer_name\x18\b \x01(\tR\tbuyerName\x12\x16\n" +
	"\x06amount\x18\t \x01(\x05R\x06amount\x12&\n" +
	"\x0fprice_per_stock\x18\n" +
	" \x01(\x01R\rpricePerStock\x12'\n" +
	"\x0fsettlement_date\x18\v \x01(\tR\x0esettlementDate\x12\x18\n" +
	"\apremium\x18\f \x01(\x01R\apremium\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12#\n" +
	"\rlast_modified\x18\x0e \x01(\tR\flastModified\x12$\n" +
	"\x0emodified_by_id\x18\x0f \x01(\x03R\fmodifiedById\x12(\n" +
	"\x10modified_by_type\x18\x10 \x01(\tR\x0emodifiedByType\x12(\n" +
	"\x10modified_by_name\x18\x11 \x01(\tR\x0emodifiedByName\x12\x16\n" +
	"\x06status\x18\x12 \x01(\tR\x06status\"X\n" +
	"\x18ListNegotiationsResponse\x12<\n" +
	"\fnegotiations\x18\x01 \x03(\v2\x18.otc.NegotiationResponseR\fnegotiations\"\x82\x04\n" +
	"\x10ContractResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12%\n" +
	"\x0enegotiation_id\x18\x02 \x01(\x03R\rnegotiationId\x12\x1b\n" +
	"\tseller_id\x18\x03 \x01(\x03R\bsellerId\x12\x1f\n" +
	"\vseller_type\x18\x04 \x01(\tR\n" +
	"sellerType\x12\x1f\n" +
	"\vseller_name\x18\x05 \x01(\tR\n" +
	"sellerName\x12\x19\n" +
	"\bbuyer_id\x18\x06 \x01(\x03R\abuyerId\x12\x1d\n" +
	"\n" +
	"buyer_type\x18\a \x01(\tR\tbuyerType\x12\x1d\n" +
	"\n" +
	"buyer_name\x18\b \x01(\tR\tbuyerName\x12\x16\n" +
	"\x06ticker\x18\t \x01(\tR\x06ticker\x12\x16\n" +
	"\x06amount\x18\n" +
	" \x01(\x05R\x06amount\x12!\n" +
	"\fstrike_price\x18\v \x01(\x01R\vstrikePrice\x12\x18\n" +
	"\apremium\x18\f \x01(\x01R\apremium\x12\x1a\n" +
	"\bcurrency\x18\r \x01(\tR\bcurrency\x12'\n" +
	"\x0fsettlement_date\x18\x0e \x01(\tR\x0esettlementDate\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\tR\tcreatedAt\x12\x16\n" +
	"\x06profit\x18\x11 \x01(\x01R\x06profit\"y\n" +
	"\x14ListContractsRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x02 \x01(\tR\n" +
	"callerType\x12#\n" +
	"\rstatus_filter\x18\x03 \x01(\tR\fstatusFilter\"L\n" +
	"\x15ListContractsResponse\x123\n" +
	"\tcontracts\x18\x01 \x03(\v2\x15.otc.ContractResponseR\tcontracts\"\xa2\x01\n" +
	"\x17ExerciseContractRequest\x12\x1f\n" +
	"\vcontract_id\x18\x01 \x01(\x03R\n" +
	"contractId\x12\x1b\n" +
	"\tcaller_id\x18\x02 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x03 \x01(\tR\n" +
	"callerType\x12(\n" +
	"\x10buyer_account_id\x18\x04 \x01(\x03R\x0ebuyerAccountId\"S\n" +
	"\x18ExerciseContractResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1f\n" +
	"\vexecuted_at\x18\x02 \x01(\tR\n" +
	"executedAt\"P\n" +
	"\x10GetMarketRequest\x12\x1b\n" +
	"\tcaller_id\x18\x01 \x01(\x03R\bcallerId\x12\x1f\n" +
	"\vcaller_type\x18\x02 \x01(\tR\n" +
	"callerType\"\xaf\x02\n" +
	"\n" +
	"MarketItem\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x05R\x06amount\x12&\n" +
	"\x0fprice_per_stock\x18\x04 \x01(\x01R\rpricePerStock\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12!\n" +
	"\flast_updated\x18\x06 \x01(\tR\vlastUpdated\x12\x1d\n" +
	"\n" +
	"owner_name\x18\a \x01(\tR\townerName\x12\x1d\n" +
	"\n" +
	"owner_bank\x18\b \x01(\tR\townerBank\x12\x19\n" +
	"\bowner_id\x18\t \x01(\x03R\aownerId\x12\x1d\n" +
	"\n" +
	"owner_type\x18\n" +
	" \x01(\tR\townerType\":\n" +
	"\x11GetMarketResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.otc.MarketItemR\x05items\"\x12\n" +
	"\x10OtcEmptyResponse\"\xaa\x04\n" +
	"!CreateInterbankNegotiationRequest\x12\x16\n" +
	"\x06ticker\x18\x01 \x01(\tR\x06ticker\x12'\n" +
	"\x0fsettlement_date\x18\x02 \x01(\tR\x0esettlementDate\x12$\n" +
	"\x0eprice_per_unit\x18\x03 \x01(\x01R\fpricePerUnit\x12%\n" +
	"\x0eprice_currency\x18\x04 \x01(\tR\rpriceCurrency\x12\x18\n" +
	"\apremium\x18\x05 \x01(\x01R\apremium\x120\n" +
	"\x14buyer_routing_number\x18\x06 \x01(\x05R\x12buyerRoutingNumber\x12*\n" +
	"\x11buyer_external_id\x18\a \x01(\tR\x0fbuyerExternalId\x122\n" +
	"\x15seller_routing_number\x18\b \x01(\x05R\x13sellerRoutingNumber\x12,\n" +
	"\x12seller_external_id\x18\t \x01(\tR\x10sellerExternalId\x124\n" +
	"\x16creator_routing_number\x18\n" +
	" \x01(\x05R\x14creatorRoutingNumber\x12.\n" +
	"\x13creator_external_id\x18\v \x01(\tR\x11creatorExternalId\x12\x16\n" +
	"\x06amount\x18\f \x01(\x05R\x06amount\x12\x1f\n" +
	"\vseller_type\x18\r \x01(\tR\n" +
	"sellerType\"\xbe\x04\n" +
	"\x1cInterbankNegotiationResponse\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x03R\alocalId\x124\n" +
	"\x16creator_routing_number\x18\x02 \x01(\x05R\x14creatorRoutingNumber\x12.\n" +
	"\x13creator_external_id\x18\x03 \x01(\tR\x11creatorExternalId\x12\x16\n" +
	"\x06ticker\x18\x04 \x01(\tR\x06ticker\x12'\n" +
	"\x0fsettlement_date\x18\x05 \x01(\tR\x0esettlementDate\x12$\n" +
	"\x0eprice_per_unit\x18\x06 \x01(\x01R\fpricePerUnit\x12%\n" +
	"\x0eprice_currency\x18\a \x01(\tR\rpriceCurrency\x12\x18\n" +
	"\apremium\x18\b \x01(\x01R\apremium\x12\x16\n" +
	"\x06amount\x18\t \x01(\x05R\x06amount\x12\x1d\n" +
	"\n" +
	"is_ongoing\x18\n" +
	" \x01(\bR\tisOngoing\x120\n" +
	"\x14buyer_routing_number\x18\v \x01(\x05R\x12buyerRoutingNumber\x12*\n" +
	"\x11buyer_external_id\x18\f \x01(\tR\x0fbuyerExternalId\x122\n" +
	"\x15seller_routing_number\x18\r \x01(\x05R\x13sellerRoutingNumber\x12,\n" +
	"\x12seller_external_id\x18\x0e \x01(\tR\x10sellerExternalId\"g\n" +
	"\x1dInterbankNegotiationIdRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\"\xe7\x01\n" +
	"\x1cInterbankCounterOfferRequest\x12%\n" +
	"\x0erouting_number\x18\x01 \x01(\x05R\rroutingNumber\x12\x1f\n" +
	"\vexternal_id\x18\x02 \x01(\tR\n" +
	"externalId\x12$\n" +
	"\x0eprice_per_unit\x18\x03 \x01(\x01R\fpricePerUnit\x12\x18\n" +
	"\apremium\x18\x04 \x01(\x01R\apremium\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x05R\x06amount\x12'\n" +
	"\x0fsettlement_date\x18\x06 \x01(\tR\x0esettlementDate2\xb1\t\n" +
	"\n" +
	"OtcService\x12+\n" +
	"\x04Ping\x12\x10.otc.PingRequest\x1a\x11.otc.PingResponse\x12L\n" +
	"\x11CreateNegotiation\x12\x1d.otc.CreateNegotiationRequest\x1a\x18.otc.NegotiationResponse\x12O\n" +
	"\x10ListNegotiations\x12\x1c.otc.ListNegotiationsRequest\x1a\x1d.otc.ListNegotiationsResponse\x12F\n" +
	"\x0eGetNegotiation\x12\x1a.otc.GetNegotiationRequest\x1a\x18.otc.NegotiationResponse\x12B\n" +
	"\fCounterOffer\x12\x18.otc.CounterOfferRequest\x1a\x18.otc.NegotiationResponse\x12L\n" +
	"\x11AcceptNegotiation\x12\x1d.otc.AcceptNegotiationRequest\x1a\x18.otc.NegotiationResponse\x12L\n" +
	"\x11RejectNegotiation\x12\x1d.otc.RejectNegotiationRequest\x1a\x18.otc.NegotiationResponse\x12F\n" +
	"\rListContracts\x12\x19.otc.ListContractsRequest\x1a\x1a.otc.ListContractsResponse\x12O\n" +
	"\x10ExerciseContract\x12\x1c.otc.ExerciseContractRequest\x1a\x1d.otc.ExerciseContractResponse\x12:\n" +
	"\tGetMarket\x12\x15.otc.GetMarketRequest\x1a\x16.otc.GetMarketResponse\x12g\n" +
	"\x1aCreateInterbankNegotiation\x12&.otc.CreateInterbankNegotiationRequest\x1a!.otc.InterbankNegotiationResponse\x12]\n" +
	"\x15InterbankCounterOffer\x12!.otc.InterbankCounterOfferRequest\x1a!.otc.InterbankNegotiationResponse\x12`\n" +
	"\x17InterbankGetNegotiation\x12\".otc.InterbankNegotiationIdRequest\x1a!.otc.InterbankNegotiationResponse\x12W\n" +
	"\x1aInterbankDeleteNegotiation\x12\".otc.InterbankNegotiationIdRequest\x1a\x15.otc.OtcEmptyResponse\x12W\n" +
	"\x1aInterbankAcceptNegotiation\x12\".otc.InterbankNegotiationIdRequest\x1a\x15.otc.OtcEmptyResponseB8Z6github.com/RAF-SI-2025/EXBanka-4-Backend/shared/pb/otcb\x06proto3"

var (
	file_otc_proto_rawDescOnce sync.Once
	file_otc_proto_rawDescData []byte
)

func file_otc_proto_rawDescGZIP() []byte {
	file_otc_proto_rawDescOnce.Do(func() {
		file_otc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_otc_proto_rawDesc), len(file_otc_proto_rawDesc)))
	})
	return file_otc_proto_rawDescData
}

var file_otc_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_otc_proto_goTypes = []any{
	(*PingRequest)(nil),                       // 0: otc.PingRequest
	(*PingResponse)(nil),                      // 1: otc.PingResponse
	(*CreateNegotiationRequest)(nil),          // 2: otc.CreateNegotiationRequest
	(*CounterOfferRequest)(nil),               // 3: otc.CounterOfferRequest
	(*AcceptNegotiationRequest)(nil),          // 4: otc.AcceptNegotiationRequest
	(*RejectNegotiationRequest)(nil),          // 5: otc.RejectNegotiationRequest
	(*ListNegotiationsRequest)(nil),           // 6: otc.ListNegotiationsRequest
	(*GetNegotiationRequest)(nil),             // 7: otc.GetNegotiationRequest
	(*NegotiationResponse)(nil),               // 8: otc.NegotiationResponse
	(*ListNegotiationsResponse)(nil),          // 9: otc.ListNegotiationsResponse
	(*ContractResponse)(nil),                  // 10: otc.ContractResponse
	(*ListContractsRequest)(nil),              // 11: otc.ListContractsRequest
	(*ListContractsResponse)(nil),             // 12: otc.ListContractsResponse
	(*ExerciseContractRequest)(nil),           // 13: otc.ExerciseContractRequest
	(*ExerciseContractResponse)(nil),          // 14: otc.ExerciseContractResponse
	(*GetMarketRequest)(nil),                  // 15: otc.GetMarketRequest
	(*MarketItem)(nil),                        // 16: otc.MarketItem
	(*GetMarketResponse)(nil),                 // 17: otc.GetMarketResponse
	(*OtcEmptyResponse)(nil),                  // 18: otc.OtcEmptyResponse
	(*CreateInterbankNegotiationRequest)(nil), // 19: otc.CreateInterbankNegotiationRequest
	(*InterbankNegotiationResponse)(nil),      // 20: otc.InterbankNegotiationResponse
	(*InterbankNegotiationIdRequest)(nil),     // 21: otc.InterbankNegotiationIdRequest
	(*InterbankCounterOfferRequest)(nil),      // 22: otc.InterbankCounterOfferRequest
}
var file_otc_proto_depIdxs = []int32{
	8,  // 0: otc.ListNegotiationsResponse.negotiations:type_name -> otc.NegotiationResponse
	10, // 1: otc.ListContractsResponse.contracts:type_name -> otc.ContractResponse
	16, // 2: otc.GetMarketResponse.items:type_name -> otc.MarketItem
	0,  // 3: otc.OtcService.Ping:input_type -> otc.PingRequest
	2,  // 4: otc.OtcService.CreateNegotiation:input_type -> otc.CreateNegotiationRequest
	6,  // 5: otc.OtcService.ListNegotiations:input_type -> otc.ListNegotiationsRequest
	7,  // 6: otc.OtcService.GetNegotiation:input_type -> otc.GetNegotiationRequest
	3,  // 7: otc.OtcService.CounterOffer:input_type -> otc.CounterOfferRequest
	4,  // 8: otc.OtcService.AcceptNegotiation:input_type -> otc.AcceptNegotiationRequest
	5,  // 9: otc.OtcService.RejectNegotiation:input_type -> otc.RejectNegotiationRequest
	11, // 10: otc.OtcService.ListContracts:input_type -> otc.ListContractsRequest
	13, // 11: otc.OtcService.ExerciseContract:input_type -> otc.ExerciseContractRequest
	15, // 12: otc.OtcService.GetMarket:input_type -> otc.GetMarketRequest
	19, // 13: otc.OtcService.CreateInterbankNegotiation:input_type -> otc.CreateInterbankNegotiationRequest
	22, // 14: otc.OtcService.InterbankCounterOffer:input_type -> otc.InterbankCounterOfferRequest
	21, // 15: otc.OtcService.InterbankGetNegotiation:input_type -> otc.InterbankNegotiationIdRequest
	21, // 16: otc.OtcService.InterbankDeleteNegotiation:input_type -> otc.InterbankNegotiationIdRequest
	21, // 17: otc.OtcService.InterbankAcceptNegotiation:input_type -> otc.InterbankNegotiationIdRequest
	1,  // 18: otc.OtcService.Ping:output_type -> otc.PingResponse
	8,  // 19: otc.OtcService.CreateNegotiation:output_type -> otc.NegotiationResponse
	9,  // 20: otc.OtcService.ListNegotiations:output_type -> otc.ListNegotiationsResponse
	8,  // 21: otc.OtcService.GetNegotiation:output_type -> otc.NegotiationResponse
	8,  // 22: otc.OtcService.CounterOffer:output_type -> otc.NegotiationResponse
	8,  // 23: otc.OtcService.AcceptNegotiation:output_type -> otc.NegotiationResponse
	8,  // 24: otc.OtcService.RejectNegotiation:output_type -> otc.NegotiationResponse
	12, // 25: otc.OtcService.ListContracts:output_type -> otc.ListContractsResponse
	14, // 26: otc.OtcService.ExerciseContract:output_type -> otc.ExerciseContractResponse
	17, // 27: otc.OtcService.GetMarket:output_type -> otc.GetMarketResponse
	20, // 28: otc.OtcService.CreateInterbankNegotiation:output_type -> otc.InterbankNegotiationResponse
	20, // 29: otc.OtcService.InterbankCounterOffer:output_type -> otc.InterbankNegotiationResponse
	20, // 30: otc.OtcService.InterbankGetNegotiation:output_type -> otc.InterbankNegotiationResponse
	18, // 31: otc.OtcService.InterbankDeleteNegotiation:output_type -> otc.OtcEmptyResponse
	18, // 32: otc.OtcService.InterbankAcceptNegotiation:output_type -> otc.OtcEmptyResponse
	18, // [18:33] is the sub-list for method output_type
	3,  // [3:18] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_otc_proto_init() }
func file_otc_proto_init() {
	if File_otc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_otc_proto_rawDesc), len(file_otc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otc_proto_goTypes,
		DependencyIndexes: file_otc_proto_depIdxs,
		MessageInfos:      file_otc_proto_msgTypes,
	}.Build()
	File_otc_proto = out.File
	file_otc_proto_goTypes = nil
	file_otc_proto_depIdxs = nil
}
